workflows:
  android-workflow:
    name: Android Build & Firebase Distribution
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      java: 17
      groups:
        - firebase_credentials
      vars:
        FIREBASE_APP_ID: "1:891051622598:android:68c9f9d42b3f233c10d7c7"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

      - name: Build AAB
        script: flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $FIREBASE_APP_ID
          groups:
            - self
          artifact_type: apk

  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic CI

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.kinesa.kinesa
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_APP_ID: "6758523369"

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios && pod install

      - name: Flutter build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true

  ios-adhoc-workflow:
    name: iOS Ad Hoc Build (Testing)
    max_build_duration: 90
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic CI

    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.kinesa.kinesa
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_IOS_APP_ID: "1:891051622598:ios:60a2b9b0d18a7fd310d7c7"

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios && pod install

      - name: Flutter build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        ios:
          app_id: $FIREBASE_IOS_APP_ID
          groups:
            - self
