workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    integrations:
      app_store_connect: Codemagic CI

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.kinesa.kinesa
      vars:
        APP_STORE_APP_ID: "6758523369"
        BUNDLE_ID: "com.kinesa.kinesa"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles --export-options-plist=/Users/builder/export_options.plist

      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - "**/*.ipa"
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

      - name: Build AAB
        script: flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
